apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    tier: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: api
    spec:
      containers:
      - name: backend
        image: laurasoy1/brian-yolo-backend:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/yolomy"
        readinessProbe:
          httpGet:
            path: /api/products
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
