- name: Build frontend Docker image
  docker_image:
    name: "{{ frontend_image }}"
    build:
      path: "{{ frontend_dir }}"
      dockerfile: Dockerfile
    source: build
    force_source: yes
  ignore_errors: yes

- name: Run Frontend Container
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "{{ frontend_image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    networks_cli_compatible: yes
    ports:
      - "{{ frontend_port }}:3000"
    env: "{{ frontend_env }}"
    volumes:
      - "{{ frontend_dir }}:/app"
    working_dir: /app
  when: use_alpine_base == false  # Skip if using custom image

- name: Run Frontend Container with Node Alpine
  docker_container:
    name: "{{ frontend_container_name }}"
    image: "node:{{ node_version }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
    networks_cli_compatible: yes
    ports:
      - "{{ frontend_port }}:3000"
    volumes:
      - "{{ frontend_dir }}:/app" 
    working_dir: /app
    command: sh -c "npm install && npm start"
    env: "{{ frontend_env }}"
  when: use_alpine_base == true